language: node_js
node_js:
  - 5
  
env:
  global:
    - NODE_ENV=development
    - CXX=g++-4.8

addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
  #code_climate:
  #    repo_token: 9c3621172d85147f3bf0fd4ff684ee77d281be37429f7f6f50922e478f377d20

services:
  - redis-server

before_script:
  - cd server
  - npm install
  - mv config-sample.json config.json
  - mv knexfile-sample.js knexfile.js
  - psql -c 'create database dev_focus;' -U postgres
  - ./node_modules/.bin/knex migrate:latest
  
script: npm run test-travis

#after_script:
#  - ./node_modules/.bin/codeclimate-test-reporter < lcov.info
