language: node_js
node_js:
  - 4

addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8

services:
  - redis-server

env:
  global:
    - NODE_ENV=development
    - CXX=g++-4.8
    
before_script:
  - cd server
  - sudo npm i -g node-gyp && node-gyp clean
  - npm install
  - mv config-sample.json config.json
  - mv knexfile-sample.js knexfile.js
  - psql -c 'create database dev_focus;' -U postgres
  - ./node_modules/.bin/knex migrate:latest
  
script: cd server && npm test
